### ISSUE TITLE
File

### ISSUE THREAD

**Issue by Data-Designer** [FengZhu-Joey/GA-DTCDR#7]
Hi, I am trying to use your model as a baseline. But I found the files for Doc2vec_douban_movie_Vsize_64, 128 are missing. Thank you very much if you can provide it.
My email is zhaochuang@tju.edu.cn.

**Comment by FengZhu-Joey** [comment]
Hi, I did not upload the pre-trained doc2vec embedding sets (size=128) because the file size limit of Github is 50M. Sadly, I cannot find these embedding sets on my computer now. But, we have provided the code of doc2vec embedding generation, you can run it to generate the corresponding embeddings by yourself.
